phantom:
  host: 'localhost'
  command: phantomjs   # phantomjs executable
  port: 3001           # internal service port. No need to allow inbound or outbound access to this port
  path: 'D:/workspace/screenshot-as-a-service/test/screenshot/original/'        # where the screenshot files are stored
  viewport: '1024x768' # browser window size. Height frows according to the content
cache:
  lifetime: 6000000000000      # one minute, set to 0 for no cache
server:
  port: 3000           # main service port
adminServer:
  port: 3002
db:
  url: 'mongodb://localhost/mynetrnd'
  collections: 'sites'
